name: GitHub Pages

on:
  push:
    branches:
      - deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - uses: jontze/action-mdbook@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          mdbook-version: "~0.4.25"
          use-mermaid: true
          mermaid-version: "~0.12.6"
          use-toc: true
          toc-version: "~0.11.0"
          use-linkcheck: false
          use-opengh: false

      - run: mdbook-mermaid install
      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/deploy' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
